name: Code Quality & Linting

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore linters cache
        uses: actions/cache@v4
        with:
          path: |
            .mypy_cache
            .ruff_cache
          key: ${{ runner.os }}-linters-${{ hashFiles('uv.lock', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-linters-

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run Quality Checks
        run: make check